### ISSUE TITLE
Consider renaming packages to disambiguate from source programs

### ISSUE THREAD

**Issue by luxaritas** [eternagame/workspace-helpers#80]
Eg, it might be better to call `@eternagame/vite` `@eternagame/vite-config`

**Comment by luxaritas** [comment]
Half of a mind to rename `workspace-helpers` too, as I'm not sure how accurate it is... could probably use discussion

**Comment by tkaragianes** [comment]
Per discussion today, plan to rename with a`-utils` suffix.
